name: Hello world workflow

on:
  push:
    branches:
      - practise/first-task
  pull_request:
    branches:
      - practise/first-task
  workflow_dispatch:
jobs:
  hello:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: hello-world
        run: echo "Hello world"
        shell: powershell
  goodbye:
    runs-on: windows-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: powershell
